### ISSUE TITLE
RangeError: The buffer's size is too big or the BlockSize is too small;the number of blocks must be <= 50000

### ISSUE THREAD

**Issue by blrchen** [blrchen/azure-speed-test#88]
Uncaught (in promise): RangeError: The buffer's size is too big or the BlockSize is too small;the number of blocks must be <= 50000
RangeError: The buffer's size is too big or the BlockSize is too small;the number of blocks must be <= 50000
    at t.<anonymous> (https://www.azurespeed.com/6-es2015.db80ad22938ee83ee112.js:1:447663)
    at https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:272709
    at Object.next (https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:272814)
    at https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:271751
    at new _ (https://www.azurespeed.com/polyfills-es2015.6d77b6423ece310014f3.js:1:102322)
    at a (https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:271525)
    at t.uploadSeekableBlob (https://www.azurespeed.com/6-es2015.db80ad22938ee83ee112.js:1:446533)
    at t.<anonymous> (https://www.azurespeed.com/6-es2015.db80ad22938ee83ee112.js:1:446106)
    at https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:272709
    at Object.next (https://www.azurespeed.com/main-es2015.1a5ed9358680957bb38a.js:1:272814)

**Comment by blrchen** [comment]
Seems no longer reproduce in latest azure storage js sdk, closing
